= Parameters

The parent key for all of the following parameters is `vshn_sli_reporting`.

== `namespace`

[horizontal]
type:: string
default:: `syn-vshn-sli-reporting`

The namespace in which to deploy this component.

== `images`

[horizontal]
type:: dict
default:: See https://github.com/vshn/component-vshn-sli-reporting/blob/master/class/defaults.yml[`class/defaults.yml`]

A list of images to be used by the component.

== `auth.user`

[horizontal]
type:: string
default:: "admin"

Username for HTTP basic authentication required by the SLI reporting API.

== `auth.password`

[horizontal]
type:: string

Password for HTTP basic authentication required by the SLI reporting API.
Required parameter.

== `db_file`
[horizontal]
type:: string
default:: "/data/data.db"

Path of the sqlite database file to use.

== `storage_requests`
[horizontal]
type:: string
default:: "1Gi"

Storage requests for the database volume.

== `lieutenant.k8s_url`
[horizontal]
type:: string

API URL where the kubernetes API of the Lieutenant cluster can be reached.
Required.

== `lieutenant.sa_token`
[horizontal]
type:: string

Service account token which is able to get clusters on the Lieutenant cluster.
Required.

== `lieutenant.namespace`
[horizontal]
type:: string
default:: lieutenant

Namespace in which Cluster resources can be found on the Lieutenant cluster.

== `network_policies.target_namespaces`

[horizontal]
type:: dictionary
default:: `{}`
example::
+
[source,yaml]
----
appuio-reporting-database: true
appuio-thanos: true
----

Injects a network policy into the target namespace given by the key, allowing communication to the namespace.

[NOTE]
This is a workaround and the parameter will disappear once we've a more native way to manage network policies with Project Syn.

== `extra_volumes`

[horizontal]
type:: dict
default:: {}

A list of additional volumes to be mounted into the container.


== Example

[source,yaml]
----
namespace: example-namespace
images:
    sli_reporting:
    registry: ghcr.io
    repository: vshn/vshn-sli-reporting
    tag: v0.1.2

auth:
    user: admin
    password: SuperSecretPassword

db_file: /data/data.db
storage_requests: 1Gi

lieutenant:
    k8s_url: https://my.lieutenant.k8s.api.url
    sa_token: eySomeApiToken
    namespace: lieutenant

extra_volumes:
    my_volume:
        mount_spec:
            mountPath: "/foo"
        volume_spec:
            emptyDir:
                sizeLimit: "500Mi"
----
