= Parameters

The parent key for all of the following parameters is `vshn_sli_reporting`.

== `namespace`

[horizontal]
type:: string
default:: `syn-vshn-sli-reporting`

The namespace in which to deploy this component.

== `images`

[horizontal]
type:: dict
default:: See https://github.com/vshn/component-vshn-sli-reporting/blob/master/class/defaults.yml[`class/defaults.yml`]

A list of images to be used by the component.

== `sli_reporting.resources`

[horizontal]
type:: dict
default::
+
[source,yaml]
----
resources:
    requests:
        cpu: 100m
        memory: 256Mi
        storage: 1Gi
    limits: {}
----

Pod resource requests and limits.

== `sli_reporting.auth.user`

[horizontal]
type:: string
default:: "admin"

Username for HTTP basic authentication required by the SLI reporting API.

== `sli_reporting.auth.password`

[horizontal]
type:: string

Password for HTTP basic authentication required by the SLI reporting API.
Required parameter.

== `sli_reporting.db_file`
[horizontal]
type:: string
default:: "/data/data.db"

Path of the sqlite database file to use.

== `storage_requests`
[horizontal]
type:: string
default:: "1Gi"

Storage requests for the database volume.

== `sli_reporting.lieutenant.k8s_url`
[horizontal]
type:: string

API URL where the kubernetes API of the Lieutenant cluster can be reached.
Required.

== `sli_reporting.lieutenant.sa_token`
[horizontal]
type:: string

Service account token which is able to get clusters on the Lieutenant cluster.
Required.

== `sli_reporting.lieutenant.namespace`
[horizontal]
type:: string
default:: lieutenant

Namespace in which Cluster resources can be found on the Lieutenant cluster.

== `network_policies.target_namespaces`

[horizontal]
type:: dictionary
default:: `{}`
example::
+
[source,yaml]
----
appuio-reporting-database: true
appuio-thanos: true
----

Injects a network policy into the target namespace given by the key, allowing communication to the namespace.

[NOTE]
This is a workaround and the parameter will disappear once we've a more native way to manage network policies with Project Syn.

== `extra_volumes`

[horizontal]
type:: dict
default:: See https://github.com/vshn/component-vshn-sli-reporting/blob/master/class/defaults.yml[`class/defaults.yml`]
example::
+
[source,yaml]
----
extra_volumes:
    vshn_sli_reporting:
        my_volume:
            mount_spec: <1>
                mountPath: "/foo"
            volume_spec: <2>
                emptyDir:
                    sizeLimit: "500Mi"
----
<1> Fields in `mount_spec` are added to the container's `volumeMount` entry for this volume.
<2> Fields in `volume_spec` are added to the pod's `volume` entry for this volume.


A list of additional volumes to be mounted into each container.


== Example

[source,yaml]
----
namespace: example-namespace
images:
    sli_reporting:
    registry: ghcr.io
    repository: vshn/vshn-sli-reporting
    tag: v0.1.2

auth:
    user: admin
    password: SuperSecretPassword

db_file: /data/data.db
storage_requests: 1Gi

lieutenant:
    k8s_url: https://my.lieutenant.k8s.api.url
    sa_token: eySomeApiToken
    namespace: lieutenant

extra_volumes:
    vshn_sli_reporting:
        my_volume:
            mount_spec:
                mountPath: "/foo"
            volume_spec:
                emptyDir:
                    sizeLimit: "500Mi"
----
